

### GET ALL Aggregate Orders

GET http://localhost:4200/aggregator/orders

###

GET http://localhost:4200/aggregator/orders?name=Watch

### GET Aggregate Order by id

GET http://localhost:4200/aggregator/orders/10


// ================================= ORDER SERVICE ===================================

### GET ALL Orders

GET http://localhost:3000/orders

### GET Order by id

GET http://localhost:3000/orders/10

### GET Products

GET http://localhost:4000/products

### POST Orders

POST http://localhost:3000/orders
Content-Type: application/json

{
  "status": "NEW",
  "lineItems": [
    {
      "productId": 4,
      "quantity": 4
    }
  ]
}

### PUT Order Status
PUT http://localhost:3000/orders/status/13
Content-Type: application/json

{
  "status": "PROCESSING"
}

### PUT Order

PUT http://localhost:3000/orders/3
Content-Type: application/json

{
  "status": "PENDING",
  "lineItems": [
    {
      "id": 2,
      "productId": 11,
      "quantity": 111
    }
  ]
}

### DELETE Order

DELETE http://localhost:3000/orders/1